/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkforceRouteImport } from './routes/workforce'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkforceIndexRouteImport } from './routes/workforce.index'
import { Route as WorkforcePortfolioRouteImport } from './routes/workforce.portfolio'
import { Route as WorkforceAiAdoptionRouteImport } from './routes/workforce.ai-adoption'

const WorkforceRoute = WorkforceRouteImport.update({
  id: '/workforce',
  path: '/workforce',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkforceIndexRoute = WorkforceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkforceRoute,
} as any)
const WorkforcePortfolioRoute = WorkforcePortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => WorkforceRoute,
} as any)
const WorkforceAiAdoptionRoute = WorkforceAiAdoptionRouteImport.update({
  id: '/ai-adoption',
  path: '/ai-adoption',
  getParentRoute: () => WorkforceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workforce': typeof WorkforceRouteWithChildren
  '/workforce/ai-adoption': typeof WorkforceAiAdoptionRoute
  '/workforce/portfolio': typeof WorkforcePortfolioRoute
  '/workforce/': typeof WorkforceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/workforce/ai-adoption': typeof WorkforceAiAdoptionRoute
  '/workforce/portfolio': typeof WorkforcePortfolioRoute
  '/workforce': typeof WorkforceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/workforce': typeof WorkforceRouteWithChildren
  '/workforce/ai-adoption': typeof WorkforceAiAdoptionRoute
  '/workforce/portfolio': typeof WorkforcePortfolioRoute
  '/workforce/': typeof WorkforceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/workforce'
    | '/workforce/ai-adoption'
    | '/workforce/portfolio'
    | '/workforce/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/workforce/ai-adoption' | '/workforce/portfolio' | '/workforce'
  id:
    | '__root__'
    | '/'
    | '/workforce'
    | '/workforce/ai-adoption'
    | '/workforce/portfolio'
    | '/workforce/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkforceRoute: typeof WorkforceRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workforce': {
      id: '/workforce'
      path: '/workforce'
      fullPath: '/workforce'
      preLoaderRoute: typeof WorkforceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workforce/': {
      id: '/workforce/'
      path: '/'
      fullPath: '/workforce/'
      preLoaderRoute: typeof WorkforceIndexRouteImport
      parentRoute: typeof WorkforceRoute
    }
    '/workforce/portfolio': {
      id: '/workforce/portfolio'
      path: '/portfolio'
      fullPath: '/workforce/portfolio'
      preLoaderRoute: typeof WorkforcePortfolioRouteImport
      parentRoute: typeof WorkforceRoute
    }
    '/workforce/ai-adoption': {
      id: '/workforce/ai-adoption'
      path: '/ai-adoption'
      fullPath: '/workforce/ai-adoption'
      preLoaderRoute: typeof WorkforceAiAdoptionRouteImport
      parentRoute: typeof WorkforceRoute
    }
  }
}

interface WorkforceRouteChildren {
  WorkforceAiAdoptionRoute: typeof WorkforceAiAdoptionRoute
  WorkforcePortfolioRoute: typeof WorkforcePortfolioRoute
  WorkforceIndexRoute: typeof WorkforceIndexRoute
}

const WorkforceRouteChildren: WorkforceRouteChildren = {
  WorkforceAiAdoptionRoute: WorkforceAiAdoptionRoute,
  WorkforcePortfolioRoute: WorkforcePortfolioRoute,
  WorkforceIndexRoute: WorkforceIndexRoute,
}

const WorkforceRouteWithChildren = WorkforceRoute._addFileChildren(
  WorkforceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkforceRoute: WorkforceRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
